[graph]
all-features = false

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Zlib",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "CDLA-Permissive-2.0",
]

[bans]
multiple-versions = "allow"
wildcards = "deny"
workspace-dependencies = ["moonlink"]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
